### ISSUE TITLE
create inmate class

### ISSUE THREAD

**Issue by JenniferLipps** [JenniferLipps/clinkedIn#1]
## User Story
As a developer, I want an Inmate class so that I can create instances of inmates within the app.

## AC
**When** I look in the Models folder
**Then** I should see an Inmate class
**And** it should define properties for Id, FirstName, LastName, ReleaseDate, FacilityId, Budget, Friends, Enemies, Services, and Interests

## Dev Notes
In the Models folder:
  - create a class called Inmate.cs and define in it the following properties:
    - Guid Id
    - string FirstName
    - string LastName
    - DateTime ReleaseDate
    - Guid FacilityId
    - Decimal Budget
    - List<Guid> Friends
    - List<Guid> Enemies
    - List<Guid> Services
    - List<Guid> Interests

**Comment by JenniferLipps** [comment]
Id
Name
ReleaseDate
Facility
Budget
Friends List (Guid)
Enemies List (Guid)
Services List (Guid)
Interests List (Guid)

**Comment by bobbybaxter** [comment]
👍
